Feature/local server component
codefori/vscode-db2i pull request #158
Opened 2023-10-17 15:48 UTC by worksofliam

Packages a specific version of the Server Component into the extension vsix, which will then be automatically installed when connected to a server.

Closes #157.

2023-10-17 18:53 UTC, william-xiang requested changes
The other two question/suggestion:
1. should the version be bumped for this change?
2. exclude the dsc.ts from the bundle

2023-10-17 18:53 UTC, william-xiang commented on src/connection/serverComponent.ts
>  // Otherwise, fall back to the working version
I guess these comments can be removed now?

2023-10-17 18:53 UTC, william-xiang commented on src/extension.ts
> +  console.log(context.extensionPath);
Not sure if this is added on purpose, seems it's for debugging only.

2023-10-17 18:53 UTC, william-xiang commented on src/connection/serverComponent.ts
> -          );
So here we will always update the server component if there is update available without letting user decide?

2023-10-17 18:53 UTC, william-xiang commented on src/connection/serverComponent.ts
> +            ServerComponent.writeOutput(JSON.stringify({remotePath, ExecutablePathDir}));
I think it's better to use the actual path value from commandResult.

2023-10-18 19:35 UTC, edmundreinhardt approved these changes

2023-11-01 17:37 UTC, william-xiang approved these changes
Approved. Thank you.

2023-11-07 17:49 UTC, worksofliam commented
@william-xiang 

1. We won't do a version bump here because we do not need to.
2. I removed `dsc.ts` from the vsix build.

2023-11-07 17:54 UTC, merged