Fixed schema objects ordering
codefori/vscode-db2i pull request #198
Opened 2024-02-20 18:32 UTC by sebjulliand

Fixes https://github.com/codefori/vscode-db2i/issues/197

The query run when fetching the objects for the schemas browser was supposed to order the items alphabetically but the `Select * (...) Union All` applied to join the queries would prevent it.

This PR fixes this and restores the alphabetical order in the schemas browser.

2024-02-20 20:03 UTC, chrjorgensen approved these changes
@sebjulliand Good catch - Mr. SqlGuru! 😉 

I approved - but it seems not to be accepted by GitHub... could it be me not having write access to this repo?

2024-02-20 21:39 UTC, davecharron requested changes

2024-02-20 21:39 UTC, davecharron commented on src/database/schemas.ts
> +            `select '${type}' as OBJ_TYPE, QSYS2.DELIMIT_NAME(SCHEMA_NAME) as NAME, SCHEMA_TEXT as TEXT, SYSTEM_SCHEMA_NAME as SYS_NAME, '' as SYS_SCHEMA, '' as SPECNAME, '' as BASE_SCHEMA, '' as BAS
Delimiting the schema name here breaks the SchemaBrowser `vscode-db2i.manageSchemaBrowserList` action, which itself applies delimiting to the schema names.  That then trickles through the schema browser tree as the name ends up double-delimited.  The SchemaBrowser handles the sorting of the schemas in its `getChildren` method.

2024-02-20 21:46 UTC, davecharron commented on src/database/schemas.ts
> +    const query = `${selects.join(" UNION ALL ")} Order by NAME asc`;
```suggestion
    const query = `${selects.join(" UNION ALL ")} Order by QSYS2.DELIMIT_NAME(NAME) asc`;
```

2024-02-21 08:17 UTC, sebjulliand commented
Thank you for your review and your suggestion @davecharron 🙏🏻
You can give it another go if you wish.

2024-02-21 16:12 UTC, davecharron approved these changes
Looks good to go!

2024-02-21 20:38 UTC, worksofliam commented
Tests are passing. Thanks @sebjulliand!!

2024-02-21 20:39 UTC, merged