Feature/new self codes
codefori/vscode-db2i pull request #207
Opened 2024-03-08 20:44 UTC by ajshedivy

### Issues:

 - #137

2024-03-12 03:25 UTC, worksofliam requested changes
Just a couple of small bits. Looks good so far. I will update your todo list with a couple more items that I want to tackle here.

2024-03-12 03:25 UTC, worksofliam commented on src/connection/sqlJob.ts
>        await this.query<any>(query).run();
Consider using the second parameter to `query`, which accepts binding parameters in place of `?` in the statement here.

2024-03-12 03:25 UTC, worksofliam commented on src/views/jobManager/jobManagerView.ts
> +      // vscode.commands.registerCommand(`vscode-db2i.jobManager.getSelfErrors`, async (node?: SQLJobItem) => {
Remove this large comment block of code. It will be in history if we need it

2024-03-12 03:29 UTC, worksofliam commented on src/views/jobManager/selfCodes/selfCodesResultsView.ts
> +      return selfCodes.map((error) => {
There is a chance that `selfCodes` can be undefined here, as `getSelfCodes` can return `undefined` if no job is running. Considering returning an empty array so then no items will show up, and then use `viewsWelcome` in the `package.json` file to have default text.

2024-03-12 03:52 UTC, worksofliam commented on src/views/jobManager/selfCodes/selfCodesResultsView.ts
> +      return selfCodes.map((error) => {
I added the if statement to make sure it is defined!

2024-03-18 15:42 UTC, worksofliam commented on src/views/jobManager/selfCodes/selfCodesResultsView.ts
> +    this.resourceUri = vscode.Uri.parse(`selfCodeTreeView:${encodeURIComponent(error.MATCHES.toString())}`);
Let's use `Uri.from` here instead of `parse`

2024-03-18 19:02 UTC, worksofliam commented on src/extension.ts
> +  const selfCodeFileDecorator = new SelfTreeDecorationProvider();
Add this to the `context.subscriptions`

2024-03-22 01:07 UTC, worksofliam commented on src/connection/sqlJob.ts
>        await this.query<any>(query).run();
We spoke with Jesse. There is a bug in the SC that stops this from working.

2024-03-22 01:19 UTC, worksofliam approved these changes
We have worked with Scott and he is happy. I have done a final code review, fixed some minor things, and it's looking sharp. Let's merge.

2024-03-22 01:19 UTC, merged

2024-03-26 12:47 UTC, forstie commented
Thanks for all the revisions.
Finally, SELF is coming center stage.