Add work to list query history by date
codefori/vscode-db2i pull request #212
Opened 2024-03-20 03:42 UTC by worksofliam

* Change how we store history internally (no longer a list of strings)
* Group statements by date
* All but first are collapsed by default

2024-03-20 19:47 UTC, davecharron commented
Should we consider generic group captions as the dates become more removed from the present?  Something like what is done in Outlook, for example.
![image](https://github.com/codefori/vscode-db2i/assets/134640655/929115bd-f5fc-41e6-a283-dac4d8a0a2c1)

2024-03-20 20:16 UTC, worksofliam commented
@davecharron I will work on that.

2024-03-22 19:27 UTC, davecharron requested changes

2024-03-22 19:27 UTC, davecharron commented on src/views/queryHistoryView.ts
> +          nodes.push(new TimePeriodNode(`Later`, laterQueries));
```suggestion
          nodes.push(new TimePeriodNode(`Older`, laterQueries));
```

2024-03-22 20:05 UTC, davecharron requested changes
Try this order

2024-03-22 20:05 UTC, davecharron commented on src/views/queryHistoryView.ts
> +          }
```suggestion
          if (queryItem.unix > monthAgo) {
             laterQueries.push(new PastQueryNode(queryItem.query));
          } else if (queryItem.unix > weekAgo) {
            monthQueries.push(new PastQueryNode(queryItem.query));
         } else if (queryItem.unix > dayAgo) {
            weekQueries.push(new PastQueryNode(queryItem.query));
         } else {
            dayQueries.push(new PastQueryNode(queryItem.query));
         }
```

2024-03-25 22:06 UTC, davecharron commented
If a query from a category other than _Past day_ is run, it gets added to the _Past day_ category, but does not get removed from the previous category.

2024-03-25 22:14 UTC, davecharron commented
> If a query from a category other than _Past day_ is run, it gets added to the _Past day_ category, but does not **always** get removed from the previous category. I'll step through the failing case to see what the deal is.

Looks like it's a weirdness where the statement ended up in two categories.  Not sure how, but could be related to the warning on this PR that testing it breaks existing history.  After manually deleting one of the instances, it behaves as expected.

2024-03-25 22:38 UTC, davecharron approved these changes

2024-03-26 03:15 UTC, merged