list tables context provider
codefori/vscode-db2i pull request #305
Opened 2024-12-14 00:11 UTC by ajshedivy

2025-01-10 16:59 UTC, worksofliam requested changes

2025-01-10 16:59 UTC, worksofliam commented on src/aiProviders/continue/listTablesContextProvider.ts
> +class ListDb2iTables implements IContextProvider {
Add a constructor here and let it have a `schema` parameter and store in a class member. Then remove `getDefaultSchema` and use the new member instead.

2025-01-10 16:59 UTC, worksofliam commented on src/aiProviders/continue/listTablesContextProvider.ts
> +  private getDefaultSchema = (): string => {
Remove this.

2025-01-10 16:59 UTC, worksofliam commented on src/aiProviders/continue/listTablesContextProvider.ts
> +export async function registerDb2iTablesProvider() {
Add parameter for `schema` here.

2025-01-10 16:59 UTC, worksofliam commented on src/aiProviders/continue/listTablesContextProvider.ts
> +  const provider = new ListDb2iTables();
Pass in `schema` here to the new constructor.

2025-01-10 16:59 UTC, worksofliam commented on src/views/jobManager/jobManagerView.ts
> +                  await registerDb2iTablesProvider();
Pass in the current schema (first item in the library list from `options`).

2025-01-14 15:52 UTC, worksofliam requested changes

2025-01-14 15:52 UTC, worksofliam commented on src/aiProviders/continue/listTablesContextProvider.ts
> +  constructor(schema: string) {
Remove line 31 (`private schema....`) and use `private` inside the constructor:

```
constructor(private schema: string) {
```

2025-01-14 15:52 UTC, worksofliam commented on src/aiProviders/continue/listTablesContextProvider.ts
> +      // HACK: re register context provider work around
Is this comment still relevant since you are not re-registering in this if block, but in the else?

2025-01-14 15:52 UTC, worksofliam commented on src/database/table.ts
> +        name ? `AND column.TABLE_NAME = ${name}` : ``,
Please do not use the string literal `${name}` in the string and instead use the binding parameter.

2025-01-14 15:55 UTC, ajshedivy commented on src/aiProviders/continue/listTablesContextProvider.ts
> +      // HACK: re register context provider work around
The hack is lines is updating the continue config access time to trigger a config reload by continue

2025-01-14 17:55 UTC, worksofliam requested changes

2025-01-14 17:55 UTC, worksofliam commented on src/views/jobManager/jobManagerView.ts
> +    const selectedSchema = selectedJob.job.options.libraries[0];
We need to add a check here to make sure `selectedJob` is not `undefined`, like the lines below.

2025-01-14 17:55 UTC, worksofliam commented on src/extension.ts
> +      registerDb2iTablesProvider(JobManager.getSelection().job.options.libraries[0]);
`getSelection` can return undefined.

2025-01-16 13:58 UTC, worksofliam approved these changes
Re-tested the changes to `getItems` and looks like we're good to go.

Thanks @ajshedivy!

2025-01-16 16:07 UTC, merged