Implement problem provider and syntax checking features
codefori/vscode-db2i pull request #307
Opened 2024-12-17 21:12 UTC by worksofliam

Introduce a problem provider that highlights SQL syntax issues and allows for configurable syntax check intervals.

2024-12-18 14:35 UTC, p-behr commented
It sure appears to provide the same syntax check as running the SQL in ACS Run SQL Scripts :-)

2024-12-18 16:50 UTC, chrjorgensen requested changes
@worksofliam Looking good and working fine with most samples. 👍 

I found one issue:

- connect to IBM i (7.5 in my test)
- open a new SQL document
- enter the following source:

```sql
update qtemp.temp_rcpout
   set COL1 = '123'
     , COL2 = replace( COL2, 'a', 'A' )
     , COL3 = replace( COL3, 'b', 'B' )
     , COL4 = 'L'
     , COL5 = '/dir1/'
     , COL6 = 0
```
- press the button to syntax check

I then get this:

![billede](https://github.com/user-attachments/assets/288ad525-4a12-47a9-bdae-5f57cdab587b)

2024-12-18 18:13 UTC, worksofliam commented
@chrjorgensen Have another look. I added some additional logic to handle when the message ID is not returned, which is why you were seeing the blank message. It actually looks like this could be a bug in the system API, and IMO shouldn't be impactful to this PR.

I also made it so `01` SQL states are warnings and not errors.

2024-12-19 14:11 UTC, worksofliam commented
@chrjorgensen I added a new VS Code configuration option to determine if warnings should be shown. It is false by default.

2025-01-08 16:03 UTC, julesyan commented
There seems to be some issue with the syntax checking running when I comment out a line. I have the following
```
stop;
stop;
stop;
```
Which produces three errors. If i press CMD + / that line gets checked correctly. But if i comment out a second line, that second line does not get checked and the error remains. Same if i comment out a third line. The order of the lines do not seem to matter.

2025-01-08 16:21 UTC, julesyan commented
Another issue found for CL commands. If i start with `CL` on a line it syntax check and gives an error. Then when i continue writing the rest of the line where it is `CL: <command>;` it never rechecks to remove the error. 
Same happens if i delete the `:` on an existing CL command, wait for syntax check, then add it back in.

2025-01-09 14:26 UTC, forstie approved these changes
Good job dealing with the side issues found during testing.
A very nice addition indeed.

2025-01-09 17:42 UTC, julesyan approved these changes

2025-01-09 17:44 UTC, julesyan reviewed
> There seems to be some issue with the syntax checking running when I comment out a line. 
Actually this is still happening

2025-01-09 19:10 UTC, merged